spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ruslan
    password: 123
    url: jdbc:postgresql://localhost:5433/coworking_service_db
  liquibase:
    enabled: true
    change-log: db/changelog/changelog.xml
    default-schema: liquibase

jwt:
  secret: fdf203scdjkfkds9sdnfasb8ica12039r1mjkc1a
  lifetime: PT3H

springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui.html

app:
  common:
    logging:
      enabled: true